<?php
// Variables
return [
  "creatorName" => "CZ App Studio",
  "creatorUrl" => "https://czappstudio.com/",
  "supportNumber" => "+91 88254 29360",
  "supportWhatsappURL" => "https://wa.me/+918825429360",
  "supportEmail" => "support@czappstudio.com",
  "templateName" => "Open Core HR",
  "templateFullName" => "Open Core HR",
  "templateSuffix" => "",
  "templateVersion" => "4.2.0",
  "templateFree" => false,
  "templateDescription" => "AI-Driven HRMS for Modern Businesses.",
  "templateKeyword" => "HRMS, HR, Management, System, Application, Software, Employee, Leave, Attendance, Payroll, Recruitment, Performance, Appraisal, Training, Development, Expense, Management, Task, Project, Team, Collaboration, Communication, Notification, Workflow, Automation, Reporting, Analytics, Dashboard, Admin, Panel",
  "licenseUrl" => "https://czappstudio.com/license/",
  "livePreview" => "https://czappstudio.com",
  "productPage" => "https://czappstudio.com",
  "support" => "https://czappstudio.com/support/",
  "activationDocs" => "https://czappstudio.com/docs/open-core-hr/product-activation/",
  "moreThemes" => "https://czappstudio.com",
  "documentation" => "https://czappstudio.com/docs/open-core-hr/",
  "changelog" => "https://czappstudio.com",
  "repository" => "https://czappstudio.com",
  "gitRepo" => "https://czappstudio.com",
  "gitRepoAccess" => "https://czappstudio.com",
  "githubFreeUrl" => "https://czappstudio.com",
  "facebookUrl" => "https://czappstudio.com",
  "twitterUrl" => "https://czappstudio.com",
  "githubUrl" => "https://czappstudio.com",
  "dribbbleUrl" => "https://czappstudio.com",
  "instagramUrl" => "https://www.instagram.com/czappstudio/",
  'linkedInUrl' => 'https://in.linkedin.com/company/cz-app-studio',
  'youtubeUrl' => 'https://www.youtube.com/@CZAppStudio',
  'appDemoLink' => 'https://drive.google.com/file/d/1YtgotCgi70DF3xjK4qAlCdkZP3KyDp9E/view?usp=sharing',
  'superAdminPanelDemoLink' => 'https://opencorehr.czappstudio.com/',
  'adminPanelDemoLink' => 'https://opencorehr.czappstudio.com/',
  'itemId' => 8849,
  'envatoItemId' => 50190332,
];
